# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab3e993eeb14e9c9884eedf5978fa17897eae5a94e64cf44ca5514137303d91e3fdc1d5410919cc37e98c3742e1b5396351aa34a31af3b4707c160190cfe70ce

test:
  secret_key_base: 781af8e446d39875e0132c421806ff83af08d22cf9e09965978112dd0016487ee0c2226acedf5d86832644287c6dbf42f0368ab7b0086cb7ba3236b3d3d63ead

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
